modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/thelani/DemonCore/issues"

[[mixins]]
config="demoncore.mixins.json"

[[mods]]
modId="demoncore"
version="1.0.2"
displayName="DemonCore"
authors="Lani"
displayURL="https://github.com/thelani/DemonCore"
logoFile="demoncore_logo.png"
description='''
Minecraft Chunk load & optimization mod

'''

[[dependencies.demoncore]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.demoncore]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
