modLoader="javafml"
loaderVersion="[4,)"

license="MIT"

[[mods]]
modId="demoncore"
version="1.0.0"
displayName="DemonCore ☢️"
description='''

'''
authors="Lani"
displayURL="https://github.com/thelani/DemonCore"

[[dependencies.demoncore]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.demoncore]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.demoncore]]
modId="create"
type="optional"
versionRange="[0.5,)"
ordering="AFTER"
side="BOTH"
